# Register Collections
collections:
  components:
    output: true
    permalink: /el-.:path

  wp:
    output: false
    permalink: /wp-.:path

# Front Matter defaults
defaults:
  - scope:
      type: "pages"
    values:
      layout: "default"

# Do not change this section settings
source: ./src
destination: ./dist

# Build settings
markdown: kramdown
exclude: []
